name: test_SDK
description: A custom SDK for Flutter WebView integration.
version: 1.0.0
publish_to: 'none' 

environment:
  sdk: ">=3.6.1 <4.0.0"

flutter:
  assets:
    - assets/index.html
    - assets/bundle.js